
export const MICRONUTRIENT_KEYS = [
    "fiber", "sugar", "sodium", "calcium", "iron", "potassium", "magnesium", "zinc", 
    "phosphorus", "iodine", "selenium", "copper", "manganese", "chromium", "molybdenum", "chloride",
    "vitaminA", "vitaminC", "vitaminD", "vitaminE", "vitaminK", "vitaminB1", "vitaminB2", 
    "vitaminB3", "vitaminB5", "vitaminB6", "vitaminB7", "folate", "vitaminB12"
] as const;

export type MicronutrientKey = typeof MICRONUTRIENT_KEYS[number];

export const NUTRIENT_LABELS: Record<MicronutrientKey, string> = {
  fiber: 'Fiber',
  sugar: 'Sugar',
  sodium: 'Sodium',
  calcium: 'Calcium',
  iron: 'Iron',
  potassium: 'Potassium',
  magnesium: 'Magnesium',
  zinc: 'Zinc',
  phosphorus: 'Phosphorus',
  iodine: 'Iodine',
  selenium: 'Selenium',
  copper: 'Copper',
  manganese: 'Manganese',
  chromium: 'Chromium',
  molybdenum: 'Molybdenum',
  chloride: 'Chloride',
  vitaminA: 'Vitamin A',
  vitaminC: 'Vitamin C',
  vitaminD: 'Vitamin D',
  vitaminE: 'Vitamin E',
  vitaminK: 'Vitamin K',
  vitaminB1: 'Thiamine (B1)',
  vitaminB2: 'Riboflavin (B2)',
  vitaminB3: 'Niacin (B3)',
  vitaminB5: 'Pantothenic Acid (B5)',
  vitaminB6: 'Vitamin B6',
  vitaminB7: 'Biotin (B7)',
  folate: 'Folate (B9)',
  vitaminB12: 'Vitamin B12',
};

export const NUTRIENT_UNITS: Record<MicronutrientKey, string> = {
  fiber: 'g',
  sugar: 'g',
  sodium: 'mg',
  calcium: 'mg',
  iron: 'mg',
  potassium: 'mg',
  magnesium: 'mg',
  zinc: 'mg',
  phosphorus: 'mg',
  iodine: 'µg',
  selenium: 'µg',
  copper: 'mg',
  manganese: 'mg',
  chromium: 'µg',
  molybdenum: 'µg',
  chloride: 'mg',
  vitaminA: 'µg',
  vitaminC: 'mg',
  vitaminD: 'µg',
  vitaminE: 'mg',
  vitaminK: 'µg',
  vitaminB1: 'mg',
  vitaminB2: 'mg',
  vitaminB3: 'mg',
  vitaminB5: 'mg',
  vitaminB6: 'mg',
  vitaminB7: 'µg',
  folate: 'µg',
  vitaminB12: 'µg',
};
