
export type LoggedFoodItem = {
    logId: string;
    foodId: string;
    name: string;
    quantity: number; // in grams
    calories: number;
    protein: number;
    carbs: number;
    fat: number;
    fiber?: number;
    sugar?: number;
    sodium?: number;
    calcium?: number;
    iron?: number;
    potassium?: number;
    magnesium?: number;
    zinc?: number;
    phosphorus?: number;
    iodine?: number;
    selenium?: number;
    copper?: number;
    manganese?: number;
    chromium?: number;
    molybdenum?: number;
    chloride?: number;
    vitaminA?: number;
    vitaminC?: number;
    vitaminD?: number;
    vitaminE?: number;
    vitaminK?: number;
    vitaminB1?: number;
    vitaminB2?: number;
    vitaminB3?: number;
    vitaminB5?: number;
    vitaminB6?: number;
    vitaminB7?: number;
    folate?: number;
    vitaminB12?: number;
};
  
export type DailyLog = {
    date: string; // YYYY-MM-DD
    totalCalories: number;
    totalProtein: number;
    totalCarbs: number;
    totalFat: number;
    totalFiber: number;
    totalSugar: number;
    totalSodium: number;
    totalCalcium: number;
    totalIron: number;
    totalPotassium: number;
    totalMagnesium: number;
    totalZinc: number;
    totalPhosphorus: number;
    totalIodine: number;
    totalSelenium: number;
    totalCopper: number;
    totalManganese: number;
    totalChromium: number;
    totalMolybdenum: number;
    totalChloride: number;
    totalVitaminA: number;
    totalVitaminC: number;
    totalVitaminD: number;
    totalVitaminE: number;
    totalVitaminK: number;
    totalVitaminB1: number;
    totalVitaminB2: number;
    totalVitaminB3: number;
    totalVitaminB5: number;
    totalVitaminB6: number;
    totalVitaminB7: number;
    totalFolate: number;
    totalVitaminB12: number;
    waterIntake: number;
    meals: {
      Breakfast: LoggedFoodItem[];
      Lunch: LoggedFoodItem[];
      Dinner: LoggedFoodItem[];
    };
};
  
export type AnalyticsData = {
    date: string;
    calories: number;
    goal: number;
    protein: number;
    carbs: number;
    fat: number;
    fiber: number;
    sugar: number;
    sodium: number;
    calcium: number;
    iron: number;
    potassium: number;
    magnesium: number;
    zinc: number;
    phosphorus: number;
    iodine: number;
    selenium: number;
    copper: number;
    manganese: number;
    chromium: number;
    molybdenum: number;
    chloride: number;
    vitaminA: number;
    vitaminC: number;
    vitaminD: number;
    vitaminE: number;
    vitaminK: number;
    vitaminB1: number;
    vitaminB2: number;
    vitaminB3: number;
    vitaminB5: number;
    vitaminB6: number;
    vitaminB7: number;
    folate: number;
    vitaminB12: number;
};
  
export type AnalyticsSummary = {
    averageCalories: number;
    averageProtein: number;
    averageCarbs: number;
    averageFat: number;
    averageFiber: number;
    averageSugar: number;
    averageSodium: number;
    averageCalcium: number;
    averageIron: number;
    averagePotassium: number;
    averageMagnesium: number;
    averageZinc: number;
    averagePhosphorus: number;
    averageIodine: number;
    averageSelenium: number;
    averageCopper: number;
    averageManganese: number;
    averageChromium: number;
    averageMolybdenum: number;
    averageChloride: number;
    averageVitaminA: number;
    averageVitaminC: number;
    averageVitaminD: number;
    averageVitaminE: number;
    averageVitaminK: number;
    averageVitaminB1: number;
    averageVitaminB2: number;
    averageVitaminB3: number;
    averageVitaminB5: number;
    averageVitaminB6: number;
    averageVitaminB7: number;
    averageFolate: number;
    averageVitaminB12: number;
    goalAchievementRate: number;
    highestCalorieDay: AnalyticsData | null;
    lowestCalorieDay: AnalyticsData | null;
    consistencyScore: number;
};
